[workspace]
members = [
    "sideko",
    "docs",
    # keep commented out for dist release (cdylib causes dist error)
    # "sideko-py",
]
resolver = "2"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
